name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build git curl

      - name: Install Geode CLI
        run: |
          curl -L https://github.com/geode-sdk/cli/releases/latest/download/geode-linux -o geode
          chmod +x geode
          sudo mv geode /usr/local/bin/

      - name: Check Geode
        run: geode --version

      - name: Build mod
        run: geode build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build/
